version: '3.8'
#docker compose -f docker-compose.dev.yml --env-file .env.dev up
services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      SERVER_PORT: 8081
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "8090:8978"
    environment:
      CB_ADMIN_NAME: admin
      CB_ADMIN_PASSWORD: admin
    volumes:
      - dbeaver-data:/opt/dbeaver/workspace

volumes:
  pgdata:
  dbeaver-data: