#server:
#  port: 8080

spring:
  application:
    name: RestDemo

  datasource:
    #url: jdbc:postgresql://postgres-db:5432/mydb
    #url: jdbc:postgresql://localhost:5432/mydb
    #username: postgres
    #password: secret
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    #driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    #database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
#  server:
#    port: ${MANAGEMENT_PORT:${server.port}}