name: RestDemo Docker VPC CI

on:
  push:
    branches: [ "multi_instance" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      #Dspring.profiles.active=test because application-test.yaml file has H2 in-mem database config
      - name: Build JAR
        #run: mvn clean package -DskipTests
        run: mvn clean package -Dspring.profiles.active=test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login \
            --username AWS \
            --password-stdin 193849564091.dkr.ecr.us-east-1.amazonaws.com

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t rest-demo:${{ env.SHORT_SHA }} .

      - name: Tag Image
        run: |
          docker tag rest-demo:${{ env.SHORT_SHA }} \
          193849564091.dkr.ecr.us-east-1.amazonaws.com/backend/rest-demo:${{ env.SHORT_SHA }}

          docker tag rest-demo:${{ env.SHORT_SHA }} \
          193849564091.dkr.ecr.us-east-1.amazonaws.com/backend/rest-demo:latest

      - name: Push Image
        run: |
          docker push 193849564091.dkr.ecr.us-east-1.amazonaws.com/backend/rest-demo:${{ env.SHORT_SHA }}
          docker push 193849564091.dkr.ecr.us-east-1.amazonaws.com/backend/rest-demo:latest

#      # =====================================================
#      # Deploy First Instance
#      # =====================================================
#      - name: Deploying first instance
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.EC2_HOST_ALB_1 }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            set -euo pipefail
#
#            DEPLOY_TIME=$(date '+%Y-%m-%d %H:%M:%S')
#            echo "Deployment time: $DEPLOY_TIME"
#
#            TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" \
#            -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
#
#            INSTANCE_ID=$(curl -s \
#            -H "X-aws-ec2-metadata-token: $TOKEN" \
#            http://169.254.169.254/latest/meta-data/instance-id)
#
#            echo "Instance ID: $INSTANCE_ID"
#
#            #INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
#            TARGET_GROUP_ARN=$(aws ssm get-parameter --name "/rest-demo/TARGET_GROUP_ARN" --with-decryption --query "Parameter.Value" --output text)
#            #Deregister instance from ALB
#            aws elbv2 deregister-targets \
#            --target-group-arn $TARGET_GROUP_ARN \
#            --targets Id=$INSTANCE_ID
#
#            echo "Waiting for ALB to drain connections..."
#            sleep 15
#
#            cd /home/ubuntu
#            TARGET_PORT=8080
#
#            # -----------------------------
#            # AWS ECR Login
#            # -----------------------------
#            aws ecr get-login-password --region us-east-1 \
#            | docker login \
#            --username AWS \
#            --password-stdin 193849564091.dkr.ecr.us-east-1.amazonaws.com
#
#            docker pull 193849564091.dkr.ecr.us-east-1.amazonaws.com/backend/rest-demo:${{ env.SHORT_SHA }}
#
#            # -----------------------------
#            # Read active deployment and SHA
#            # -----------------------------
#            #CURRENT_SHA=$(cat active_sha)
#            CURRENT_SHA=$(cat active_sha 2>/dev/null || echo "none")
#
#            echo "Current active SHA: $CURRENT_SHA"
#
#            # Save  previous SHA for rollback
#            echo "$CURRENT_SHA" > previous_sha
#            PREVIOUS_SHA=$(cat previous_sha)
#
#            # -----------------------------
#            # Fetch secrets from Parameter Store
#            # -----------------------------
#            echo "Fetching secrets from AWS Parameter Store"
#
#            #DB_URL=$(aws ssm get-parameter --name "/rest-demo/DB_URL" --with-decryption --query "Parameter.Value" --output text)
#            #DB_USERNAME=$(aws ssm get-parameter --name "/rest-demo/DB_USERNAME" --with-decryption --query "Parameter.Value" --output text)
#            #DB_PASSWORD=$(aws ssm get-parameter --name "/rest-demo/DB_PASSWORD" --with-decryption --query "Parameter.Value" --output text)
#            #DB_DRIVER=$(aws ssm get-parameter --name "/rest-demo/DB_DRIVER" --with-decryption --query "Parameter.Value" --output text)
#            #DB_DIALECT=$(aws ssm get-parameter --name "/rest-demo/DB_DIALECT" --with-decryption --query "Parameter.Value" --output text)
#
#            # -----------------------------
#            # Cleanup container if exists
#            # -----------------------------
#            docker rm -f rest-demo || true
#
#            # -----------------------------
#            # Run new container
#            # -----------------------------
#            docker run -d \
#              -p $TARGET_PORT:8080 \
#              --name rest-demo \
#              --restart unless-stopped \
#              193849564091.dkr.ecr.us-east-1.amazonaws.com/backend/rest-demo:${{ env.SHORT_SHA }}
#
#            # -----------------------------
#            # Health check
#            # -----------------------------
#            HEALTH_OK=false
#            for i in {1..12}; do
#              RESPONSE=$(curl -s -m 3 http://localhost:$TARGET_PORT/actuator/health || true)
#              echo "Attempt $i: $RESPONSE"
#              if echo "$RESPONSE" | grep -q '"status":"UP"'; then
#                HEALTH_OK=true
#                break
#              fi
#              sleep 5
#            done
#
#            FINAL_PORT=$TARGET_PORT
#            FINAL_SHA=${{ env.SHORT_SHA }}
#
#            # -----------------------------
#            # Rollback if health check fails
#            # -----------------------------
#            if [ "$HEALTH_OK" != "true" ]; then
#              echo "Health check failed — rolling back"
#
#              docker stop rest-demo || true
#              docker rm -f rest-demo || true
#
#              if [ "$PREVIOUS_SHA" != "none" ]; then
#                PREVIOUS_SHA=$(cat previous_sha)
#                echo "Rolling back to previous SHA: $PREVIOUS_SHA"
#
#                docker run -d \
#                  -p $TARGET_PORT:8080 \
#                  --name rest-demo \
#                  --restart unless-stopped \
#                  193849564091.dkr.ecr.us-east-1.amazonaws.com/backend/rest-demo:$PREVIOUS_SHA
#              else
#                echo "Initial deployment failed"
#              fi
#              FINAL_SHA=$PREVIOUS_SHA
#            fi
#
#            echo $FINAL_SHA > active_sha
#
#            # -----------------------------
#            # Cleanup dangling images
#            # -----------------------------
#            docker image prune -f
#
#            # -----------------------------
#            # Log deployment
#            # -----------------------------
#            echo "$DEPLOY_TIME - Deploy successful - SHA $FINAL_SHA " >> deploy-history.log
#
#            #Registering instance back to ALB
#            aws elbv2 register-targets \
#            --target-group-arn $TARGET_GROUP_ARN \
#            --targets Id=$INSTANCE_ID
#
#            echo "Deployment complete"

      - name: Deploying first instance via SSM
        run: |
          echo "Finding first EC2 instance..."
          
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=devops-demo-ec2" "Name=instance-state-name,Values=running" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)
          
          echo "Instance ID: $INSTANCE_ID"
          
          echo "Sending deployment command via SSM..."
          
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy rest-demo" \
            --parameters 'commands=[
              "set -euo pipefail",
              "echo Starting deployment",
              "cd /home/ubuntu",
          
              "TOKEN=$(curl -X PUT http://169.254.169.254/latest/api/token -H \"X-aws-ec2-metadata-token-ttl-seconds: 21600\")",
              "INSTANCE_ID=$(curl -s -H \"X-aws-ec2-metadata-token: $TOKEN\" http://169.254.169.254/latest/meta-data/instance-id)",
          
              "TARGET_GROUP_ARN=$(aws ssm get-parameter --name /rest-demo/TARGET_GROUP_ARN --with-decryption --query Parameter.Value --output text)",
          
              "aws elbv2 deregister-targets --target-group-arn $TARGET_GROUP_ARN --targets Id=$INSTANCE_ID",
          
              "sleep 15",
          
              "sudo aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 193849564091.dkr.ecr.us-east-1.amazonaws.com",
          
              "sudo docker pull 193849564091.dkr.ecr.us-east-1.amazonaws.com/backend/rest-demo:${{ env.SHORT_SHA }}",
          
              "sudo docker rm -f rest-demo || true",
          
              "sudo docker run -d -p 8080:8080 --name rest-demo --restart unless-stopped 193849564091.dkr.ecr.us-east-1.amazonaws.com/backend/rest-demo:${{ env.SHORT_SHA }}",
          
              "aws elbv2 register-targets --target-group-arn $TARGET_GROUP_ARN --targets Id=$INSTANCE_ID",
          
              "echo Deployment complete"
            ]'            


      # =====================================================
      # Check health after First instance deployment
      # =====================================================
      - name: Wait for ALB Healthy
        run: |
          echo "Waiting for ALB health..."
          for i in {1..20}; do
            RESPONSE=$(curl -s http://${{ secrets.ALB_DNS }}/actuator/health || true)
            echo "Attempt $i: $RESPONSE"
            if echo "$RESPONSE" | grep -q '"status":"UP"'; then
              echo "ALB healthy"
              break
            fi
            sleep 10
          done

#      # =====================================================
#      # Deploy Second Instance
#      # =====================================================
#      - name: Deploying second instance
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.EC2_HOST_ALB_2 }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            set -euo pipefail
#
#            DEPLOY_TIME=$(date '+%Y-%m-%d %H:%M:%S')
#            echo "Deployment time: $DEPLOY_TIME"
#
#            TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" \
#            -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
#
#            INSTANCE_ID=$(curl -s \
#            -H "X-aws-ec2-metadata-token: $TOKEN" \
#            http://169.254.169.254/latest/meta-data/instance-id)
#
#            echo "Instance ID: $INSTANCE_ID"
#
#            #INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
#            TARGET_GROUP_ARN=$(aws ssm get-parameter --name "/rest-demo/TARGET_GROUP_ARN" --with-decryption --query "Parameter.Value" --output text)
#            #Deregister instance from ALB
#            aws elbv2 deregister-targets \
#            --target-group-arn $TARGET_GROUP_ARN \
#            --targets Id=$INSTANCE_ID
#
#            echo "Waiting for ALB to drain connections..."
#            sleep 15
#
#            cd /home/ubuntu
#            TARGET_PORT=8080
#
#            # -----------------------------
#            # AWS ECR Login
#            # -----------------------------
#            aws ecr get-login-password --region us-east-1 \
#            | docker login \
#            --username AWS \
#            --password-stdin 193849564091.dkr.ecr.us-east-1.amazonaws.com
#
#            docker pull 193849564091.dkr.ecr.us-east-1.amazonaws.com/backend/rest-demo:${{ env.SHORT_SHA }}
#
#            # -----------------------------
#            # Read active deployment and SHA
#            # -----------------------------
#            #CURRENT_SHA=$(cat active_sha)
#            CURRENT_SHA=$(cat active_sha 2>/dev/null || echo "none")
#
#            echo "Current active SHA: $CURRENT_SHA"
#
#            # Save  previous SHA for rollback
#            echo "$CURRENT_SHA" > previous_sha
#            PREVIOUS_SHA=$(cat previous_sha)
#
#            # -----------------------------
#            # Fetch secrets from Parameter Store
#            # -----------------------------
#            echo "Fetching secrets from AWS Parameter Store"
#
#            #DB_URL=$(aws ssm get-parameter --name "/rest-demo/DB_URL" --with-decryption --query "Parameter.Value" --output text)
#            #DB_USERNAME=$(aws ssm get-parameter --name "/rest-demo/DB_USERNAME" --with-decryption --query "Parameter.Value" --output text)
#            #DB_PASSWORD=$(aws ssm get-parameter --name "/rest-demo/DB_PASSWORD" --with-decryption --query "Parameter.Value" --output text)
#            #DB_DRIVER=$(aws ssm get-parameter --name "/rest-demo/DB_DRIVER" --with-decryption --query "Parameter.Value" --output text)
#            #DB_DIALECT=$(aws ssm get-parameter --name "/rest-demo/DB_DIALECT" --with-decryption --query "Parameter.Value" --output text)
#
#            # -----------------------------
#            # Cleanup container if exists
#            # -----------------------------
#            docker rm -f rest-demo || true
#
#            # -----------------------------
#            # Run new container
#            # -----------------------------
#            docker run -d \
#              -p $TARGET_PORT:8080 \
#              --name rest-demo \
#              --restart unless-stopped \
#              193849564091.dkr.ecr.us-east-1.amazonaws.com/backend/rest-demo:${{ env.SHORT_SHA }}
#
#            # -----------------------------
#            # Health check
#            # -----------------------------
#            HEALTH_OK=false
#            for i in {1..12}; do
#              RESPONSE=$(curl -s -m 3 http://localhost:$TARGET_PORT/actuator/health || true)
#              echo "Attempt $i: $RESPONSE"
#              if echo "$RESPONSE" | grep -q '"status":"UP"'; then
#                HEALTH_OK=true
#                break
#              fi
#              sleep 5
#            done
#
#            FINAL_PORT=$TARGET_PORT
#            FINAL_SHA=${{ env.SHORT_SHA }}
#
#            # -----------------------------
#            # Rollback if health check fails
#            # -----------------------------
#            if [ "$HEALTH_OK" != "true" ]; then
#              echo "Health check failed — rolling back"
#
#              docker stop rest-demo || true
#              docker rm -f rest-demo || true
#
#              if [ "$PREVIOUS_SHA" != "none" ]; then
#                PREVIOUS_SHA=$(cat previous_sha)
#                echo "Rolling back to previous SHA: $PREVIOUS_SHA"
#
#                docker run -d \
#                  -p $TARGET_PORT:8080 \
#                  --name rest-demo \
#                  --restart unless-stopped \
#                  193849564091.dkr.ecr.us-east-1.amazonaws.com/backend/rest-demo:$PREVIOUS_SHA
#              else
#                echo "Initial deployment failed"
#              fi
#              FINAL_SHA=$PREVIOUS_SHA
#            fi
#
#            echo $FINAL_SHA > active_sha
#
#            # -----------------------------
#            # Cleanup dangling images
#            # -----------------------------
#            docker image prune -f
#
#            # -----------------------------
#            # Log deployment
#            # -----------------------------
#            echo "$DEPLOY_TIME - Deploy successful - SHA $FINAL_SHA " >> deploy-history.log
#
#            #Registering instance back to ALB
#            aws elbv2 register-targets \
#            --target-group-arn $TARGET_GROUP_ARN \
#            --targets Id=$INSTANCE_ID
#
#            echo "Deployment complete"
